cases: 
  expired:
    url: https://expired.badssl.com/
  wrong-host:
    url: https://wrong-host.badssl.com/
  self-signed:
    url: https:/self-signed.badssl.com/
  untrusted-root:
    url: https://untrusted-root.badssl.com/
  revoked:
    url: https://revoked.badssl.com/
  ok-ev:
    url: https://extended-validation.badssl.com/
  ok-ov:
    url: https://badssl.com/
  http:
    url: https://http.badssl.com/
  mixed-content:
    url: https://mixed.badssl.com/

browserIDs:
#  - firefox
  - chromium
#  - chrome
#  - opera
#  - ie
#  - edge

browsers:
  firefox:
    name: Mozilla Firefox
    package: firefox
    binary: firefox
    test-versions:
      - 47.0
    # - 49.0
    # - 46.0
    versions:
      - 69.0
      - 68.0
      - 67.0
      - 66.0
      - 65.0
      - 64.0 
      - 63.0 
      - 62.0 
      - 61.0 
      - 60.0 
      - 59.0 
      - 58.0 
      - 57.0 
      - 56.0 
      - 55.0 
      - 54.0 
      - 53.0 
      - 52.0
      - 51.0
      - 50.0
      - 49.0
      - 48.0
      - 47.0
      - 46.0 
      - 45.0 
      - 44.0 
      - 43.0 
      - 42.0 
      - 41.0 
      - 40.0 
      - 39.0 
      - 38.0 
      - 37.0 
      - 36.0 
      - 35.0 
      - 33.1 
      - 33.0 
      - 32.0 
      - 31.0 
      - 30.0 
      - 29.0 
      - 28.0 
      - 27.0 
      - 26.0 
      - 25.0 
      - 24.0 
      - 23.0 
      - 22.0 
      - 21.0 
      - 19.0 
      - 18.0 
      - 15.0
    installFolders:
      - C:\Program Files\Mozilla Firefox
      - C:\Program Files (x86)\Mozilla Firefox
      - C:\Program Files (x86)\Mozilla Maintenance Service
      - C:\Users\IEUser\AppData\Local\Mozilla
    profileFolders: C:\Users\IEUser\AppData\Roaming\Mozilla
  opera:
    name: Opera
    package: opera
    binary: opera
    test-versions:
      - 56.0.3051.116
      - 46.0.2597.61
      - 38.0.2220.41
    versions:
      - 58.0.3135.118 
      - 57.0.3098.116 
      - 56.0.3051.116 
      - 55.0.2994.61 
      - 54.0.2952.71 
      - 53.0.2907.110 
      - 52.0.2871.99 
      - 51.0.2830.55 
      - 50.0.2762.67 
      - 49.0.2725.64 
      - 48.0.2685.52 
      - 47.0.2631.80 
      - 46.0.2597.61 
      - 45.0.2552.898 
      - 44.0.2510.1457 
      - 43.0.2442.991 
      - 42.0.2393.94 
      - 41.0.2353.69 
      - 40.0.2308.90 
      - 39.0.2256.48 
      - 38.0.2220.41 
      - 37.0.2178.54 
      - 36.0.2130.65 
      - 35.0.2066.92 
      - 34.0.2036.50 
      - 33.0.1990.58 
      - 32.0.1948.69 
      - 31.0.1889.99 
      - 30.0.1835.88 
      - 29.0.1795.60 
      - 28.0.1750.51 
      - 27.0.1689.76 
      - 26.0.1656.60 
      - 25.0.1614.71 
      - 24.0.1558.64 
      - 23.0.1522.77 
      - 22.0.1471.70 
      - 21.0.1432.68 
      - 20.0.1387.91 
      - 19.0.1326.63 
      - 18.0.1284.68 
      - 17.0.1241.53 
      - 16.0.1196.80 
      - 15.0.1147.141 
      - 12.15
    installFolders:
      - C:\Users\IEUser\AppData\Local\Programs\Opera
      - C:\Users\IEUser\AppData\Local\Opera Software
    profileFolders: C:\Users\IEUser\AppData\Roaming\Opera Software
  chromium:
    name: Chromium
    package: chromium
    binary: chrome
    test-versions:
      #- 73.0.3683.75
      - 53.0.2784.0
      # - 45.0.2454.0
    versions:
      - 79.0.3913.0-snapshots
      - 78.0.3901.0-snapshots
      - 77.0.3865.0-snapshots
      - 76.0.3809.0-snapshots
      - 75.0.3770.142
      - 73.0.3683.103
      - 72.0.3626.121
      - 71.0.3578.98
      - 70.0.3538.110
      - 69.0.3497.100
      - 68.0.3440.106
      - 67.0.3396.99
      - 66.0.3359.181
      - 65.0.3325.181
      - 64.0.3282.186
      - 63.0.3239.132
      - 62.0.3202.94
      - 61.0.3163.0
      - 60.0.3112.0
      - 59.0.3071.0
      - 58.0.3029.0
      - 57.0.2987.0
      - 56.0.2924.0
      - 55.0.2882.0
      - 54.0.2840.0
      - 53.0.2784.0
      - 51.0.2683.0
      - 50.0.2661.0
      - 49.0.2598.0
      - 48.0.2564.0
      - 47.0.2526.0
      - 46.0.2490.0
      - 45.0.2454.0
      - 44.0.2403.0
      - 41.0.2255.0
      - 40.0.2211.0
      - 39.0.2171.0
      - 38.0.2125.0
      - 37.0.2061.0
      - 36.0.1978.0
      - 35.0.1916.0
      - 34.0.1848.0
      - 33.0.1732.0
      - 32.0.1701.0
      - 31.0.1650.4
      - 30.0.1599.14
    installFolders:
      - C:\Program Files (x86)\Google
      - C:\Program Files (x86)\Chromium
      - C:\Users\IEUser\AppData\Local\Chromium
      - C:\Users\IEUser\AppData\Local\Google
    profileFolders: (no chrome profile)
  chrome:
    name: Google Chrome
    package: googlechrome
    binary: chrome
    test-versions:
      #- 75.0.3770.142
      - 50.0.2661.102
      #- 54.0.2840.0
    versions:
      - 75.0.3770.100
      - 74.0.3729.169
      - 73.0.3683.103
      - 72.0.3626.121
      - 71.0.3578.98
      - 70.0.3538.11000
      - 69.0.3497.10000
      - 68.0.3440.10600
      - 67.0.3396.9900
      - 66.0.3359.18100
      - 65.0.3325.18100
      - 64.0.3282.18600
      - 63.0.3239.132
      - 62.0.3202.94
      - 61.0.3163.100
      - 60.0.3112.113
      - 59.0.3071.115
      - 58.0.3029.110
      - 57.0.2987.13301
      - 56.0.2924.87001
      - 55.0.2883.87
      - 54.0.2840.99
      - 53.0.2785.143
      - 52.0.2743.116
      - 51.0.2704.106
      - 50.0.2661.102
      - 49.0.2623.112
      - 48.0.2564.116
      - 47.0.2526.111
      - 37.0.2062.94
      - 36.0.1985.143
      - 35.0.1916.153
      - 38.0.2125.0
      - 34.0.1847.11601
      - 33.0.1750.154
      - 32.0.1700.107
      - 31.0.1650.63
      - 30.0.1599.101
      - 29.0.1547.76
      - 28.0.1500.95
      - 27.0.1453.116
      - 26.0.1410.64
      - 10.0.0
    installFolders:
      - C:\Program Files (x86)\Google
      - C:\Program Files (x86)\Chrome
      - C:\Users\IEUser\AppData\Local\Chrome
      - C:\Users\IEUser\AppData\Local\Google
    profileFolders: (no chrome profile)
  ie:
    name: Internet Explorer
    package: ie11
    binary: ie
    versions:
      - 0.2
    installFolders:
      - C:\Program Files\internet explorer
  edge:
    name: Microsoft Edge
    package: edge
    binary: edge
    versions:
      - 44